name: Python code formatting | Black

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: pip install black

      - name: Code formatting with black
        run: black .
